title: Clok
email: clok@kjellhanken.de
description: >- # this means to ignore newlines until "baseurl:"
  The minimalist smart clok you need!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://clok.kjellhanken.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kjell5317

# Build settings
theme: minima
plugins:
  - jekyll-feed
